name: Deploy PipBoy to Pi

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest # This builds on GitHub's servers rather than the PI, due to restricted resources
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Build Frontend
        run: |
          cd src/PipBoy.Client
          npm install
          npm run build

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      # Targeting Raspberry Pi architecture
      # bundle to false as we installed .NET on the Pi already
      - name: Publish Backend
        run: |
          dotnet publish src/PipBoy.Server/Pipboy.csproj \
            -c Release \
            -o ./publish \
            -r linux-arm \            
            --self-contained false \

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: pipboy-bundle # Name of the artifact zip
          path: ./publish #must correspond to the output folder of the publish step

  deploy:
    needs: build
    runs-on: self-hosted # This runs on the Pi
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: pipboy-bundle # Name of the artifact zip
          path: ./app  # Destination folder on the Pi. Magically knows it must take the artifact from .publish

      - name: Permissions & Restart
        run: |
          chmod +x ./app/Pipboy
          echo "App is updated in ~/actions-runner/_work/${{ github.event.repository.name }}/${{ github.event.repository.name }}/app"