name: Deploy PipBoy to Pi

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest # This builds on GitHub's servers rather than the PI, due to restricted resources
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Build Frontend
        run: |
          cd src/PipBoy.Client
          npm install
          npm run build

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      # Targeting Raspberry Pi architecture
      # bundle to false as we installed .NET on the Pi already
      - name: Publish Backend
        run: |
          dotnet publish src/PipBoy.Server/Pipboy.csproj \
            -c Release \
            -o ./publish \
            -r linux-arm \
            --self-contained false

          mkdir -p ./publish/scripts
          cp ./src/scripts/launch_pipboy.sh ./publish/scripts/
          cp ./src/scripts/pipboy.service ./publish/scripts/
          chmod +x ./publish/scripts/launch_pipboy.sh
          chmod +x ./publish/scripts/pipboy.service

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: pipboy-bundle # Name of the artifact zip
          path: ./publish #must correspond to the output folder of the publish step

  deploy:
    needs: build
    runs-on: self-hosted # This runs on the Pi
    steps:
      - name : Shutdown app
        run : |
          # pkill -f Pipboy || echo "No existing app process found"
          sudo systemctl stop pipboy.service || echo "No existing service found"

      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: pipboy-bundle # Name of the artifact zip
          path: ${{ github.workspace }}/app  # Destination folder on the Pi. Magically knows it must take the artifact from .publish

      - name : Verify Download
        run: ls -R ${{ github.workspace }}/app
        
      - name: Sync Systemd service
        run: |
          set -x
          ls -lh ${{ github.workspace }}/app/scripts/pipboy.service
          sudo cp -v ${{ github.workspace }}/app/scripts/pipboy.service /etc/systemd/system/pipboy.service
          sudo systemctl daemon-reload -v ||echo "Daemon-Reload had no output, should means success"

      - name: Permissions & Restart
        run: |
          chmod +x ./app/Pipboy
          chmod +x ./app/scripts/launch_pipboy.sh
          echo "App is updated in ${{ github.workspace }}/app"

      - name: Start app
        run : |
          set -x
          sudo systemctl start pipboy.service || {
            echo "Failed to start pipboy.service"
            sudo journalctl -u pipboy.service -n 20 --no-pager --since "5 minutes ago"
            exit 1
          }
          sleep 2
          sudo systemctl is-active pipboy.service